spring:
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 127.0.0.1
  cloud:
    stream:
      bindings:
        greetingChannel:
          destination: greetings

server:
  port: 8089



